FROM ksilva/dotnet-trace-base

WORKDIR /code

COPY app/ .
RUN dotnet publish ./api.test/api.test.csproj -r linux-x64 --self-contained

RUN cp /root/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.0.0/tools/crossgen \
    /code/api.test/bin/Debug/netcoreapp2.0/linux-x64/publish/
RUN cp /root/.nuget/packages/runtime.linux-x64.microsoft.netcore.app/2.0.0/tools/crossgen \
    /usr/share/dotnet/shared/Microsoft.NETCore.App/2.0.3/

RUN echo "#!/bin/bash" >> entrypoint.sh \
    && echo '/code/dntrace.sh -d 20 alloc gc heap exc > $RESULT_PATH' >> entrypoint.sh \
    && echo "dotnet vstest /code/api.test/bin/Debug/netcoreapp2.0/linux-x64/publish/api.test.dll" >> entrypoint.sh \
    && echo "sleep 20" >> entrypoint.sh \
    && chmod +x entrypoint.sh

CMD ["./entrypoint.sh"]